;
;  SCONDIN.MAC --
;	Conditional Input Routine
;	When called, returns w/zero flag set if character not available
;	  from CON: or character in A and flag not zero if character
;	  available
;	Only PSW affected
;

;  Externals --
	EXT	CST	; CONSOLE STATUS ROUTINE (A=1 IF NOT RDA)
	EXT	CIN	; CONSOLE INPUT ROUTINE

CONDIN::
	CALL	CST	; GET STATUS
	ANI	1	; MASK LSB
	CPI	1	; SET ZERO FLAG (Z=NOT RDA)
	RZ
	CALL	CIN	; GET CHAR
	RET

	END
